name: Continuouse Deployment to github pages
  on:
    push:
      branches:
        - main
  jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v3
          with:
            version:  18.x
        - name: Checkout branch
          uses: actions/checkout@v3

        - name: Clean install dependencies
          run: npm ci

        - name: Run deploy script
          run: |
            git config user.name "Mary" && git config user.email "mary.pommer@tptlive.ee"
            npm run gh-pages-deploy